name: sketchy_coins
description: A Blockchain transaction server.
version: 0.0.4
homepage: https://www.example.com

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  crypto: ^3.0.1
  hex: ^0.2.0
  uuid: ^3.0.3
  shelf_router: ^1.0.0
  json_annotation: ^4.0.1
  timeago: ^3.0.2
  jaguar_jwt: ^3.0.0
  hive: ^2.0.2
  hive_generator: ^1.0.1

dev_dependencies:
  test: ^1.14.4
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  build_web_compilers: ^2.16.5
