name: sketchy_coins
description: A Blockchain Transaction Server.
version: 0.3.1
homepage: https://www.example.com

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  crypto: ^3.0.1
  hex: ^0.2.0
  uuid: ^3.0.3
  shelf_router: ^1.0.0
  json_annotation: ^4.0.1
  hive: ^2.0.2
  hive_generator: ^1.0.1
  redis_dart: ^0.1.0+4
  dart_jsonwebtoken: ^2.1.0
  validators: ^3.0.0
  postgrest: ^0.1.0
  timeago: ^3.0.2
  supabase: ^0.0.1-dev.14

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.14.4
  build_runner: ^2.0.2
  json_serializable: ^4.1.0
  build_web_compilers: ^3.0.0
  envify_generator: ^2.0.0
