name: sketchy_coins
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  crypto: ^3.0.1
  hex: ^0.2.0
  uuid: ^3.0.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
