name: sketchy_coins
description: A Blockchain Transaction Server.
version: 0.1.5
homepage: https://www.example.com

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  crypto: ^3.0.1
  hex: ^0.2.0
  uuid: ^3.0.3
  shelf_router: ^1.0.0
  json_annotation: ^4.0.1
  hive: ^2.0.2
  hive_generator: ^1.0.1
  dotenv: ^3.0.0-nullsafety.0
  envify: ^2.0.0
  redis_dart: ^0.1.0+4
  dart_jsonwebtoken: ^2.1.0
  validators: ^3.0.0
  cryptography: ^2.0.1
  shelf_web_socket: ^1.0.1
  crdt: ^4.0.1
  geodesy: ^0.4.0-nullsafety.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.14.4
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  build_web_compilers: ^2.12.2
  envify_generator: ^2.0.0
